Pandas is one of the key data structures in python, you have encountered it before... Similar to an excel table, we have columns and rows. 

You can use dictionaries to make a pandas dataframe however that is not ideal. It is better to import from csv files. 

By default, the index is set as an integer, you have to specify the index if you want one.

In [8]:
import pandas as pd
import numpy as np

stock_pitches = pd.read_csv("stocks_pitches.csv")

stock_pitches

,Name,Associate,Ticker,Pitch Date,Pitch Price,Curr,Today Price,Price %,Total Divs,Currency ?,Total %
0,ABB Ltd,Matt Smith,ABB,06/03/2018,22.80,CHF,21.86,-0.04,1.623,1.02,0.03
1,Alibaba Group Holding Ltd,Anna Erofeeva,BABA,05/12/2017,177.62,USD,186.78,0.05,0.000,1.04,0.05
2,Apple Inc,Darren Wyy,AAPL,16/01/2018,176.30,USD,261.78,0.48,5.860,1.06,0.55
3,Arista Networks Inc,Xu Jiawei,ANET,14/11/2017,225.50,USD,194.49,-0.14,0.000,1.02,-0.14
4,BHP Billiton Ltd,Matt Smith,BHP,05/12/2017,42.10,USD,50.84,0.21,7.060,1.04,0.39
5,BlackRock Inc,Marcus McLaney,BLK,27/02/2018,563.97,USD,485.00,-0.14,21.920,1.07,-0.11
6,Domino's Pizza Inc,Dev Singh,DPZ,12/12/2017,180.96,USD,285.76,0.58,4.610,1.03,0.62
7,Estee Lauder Companies Inc,Kelvin Fang,EL,20/02/2018,139.65,USD,193.18,0.38,2.860,1.08,0.44
8,Foot Locker Inc,Arjun Kandola,FL,06/03/2018,42.10,USD,40.25,-0.04,2.520,1.07,0.02
9,General Motors Co,Matt Smith,GM,30/01/2018,42.41,USD,35.33,-0.17,2.660,1.08,-0.11
10,Honeywell International Inc.,Darren Wyy,HON,13/03/2018,145.90,USD,176.79,0.21,5.670,1.07,0.27
11,Intertek Group plc,Joshua Zeng,ITRK.L,23/01/2018,5178.00,GBX,5504.00,0.06,181.100,1.00,0.10
12,Kraft Heinz Co,Joshua Zeng,KHC,19/03/2018,67.23,USD,30.54,-0.55,3.475,1.07,-0.53
13,Marriott International Inc,Jerry Kim,MAR,20/02/2018,140.44,USD,136.25,-0.03,3.410,1.08,-0.01
14,Mastercard Inc,Kelvin Fang,MA,28/11/2017,154.77,USD,282.57,0.83,2.320,1.03,0.87
15,On The Beach Group plc,Edmund Xia,OTB.L,30/01/2018,492.00,GBX,434.60,-0.12,4.600,1.00,-0.11
16,Overstock,Anna Erofeeva,OSTK,27/02/2018,64.40,USD,7.57,-0.88,0.000,1.07,-0.94
17,Royal Carribean Cruises Ltd,Marcus McLaney,RCL,09/01/2018,123.18,USD,119.13,-0.03,4.780,1.05,0.01
18,Ryanair Holdings,Charlotte Pinder,RYA.L,16/01/2018,16.53,EUR,13.69,-0.17,0.000,0.97,-0.17
19,Siemens AG,Amos Jaupi,SIEGY,12/12/2017,116.42,EUR,63.24,-0.46,4.329,0.97,-0.41
20,St Microelectronics,Adam Barbarowicz,STM,06/02/2018,18.34,EUR,23.87,0.30,0.420,0.97,0.31
21,Starbucks Corp,Dev Singh,SBUX,28/11/2017,55.91,USD,83.02,0.48,2.810,1.03,0.55
22,Supernus Pharmaceuticals Inc,Arjun Kandola,SUPN,23/01/2018,44.25,USD,21.76,-0.51,0.000,1.08,-0.55
23,US Concrete Inc,Charlotte Pinder,USCR,13/03/2018,65.20,USD,39.96,-0.39,0.000,1.07,-0.41
24,US Silica Holdings Inc,Dev Singh,SLCA,19/03/2018,25.83,USD,4.55,-0.82,0.375,1.07,-0.87
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
stock_pitches = pd.read_csv("stocks_pitches.csv", index_col = 2)

stock_pitches

,Name,Associate,Pitch Date,Pitch Price,Curr,Today Price,Price %,Total Divs,Currency ?,Total %
Ticker,,,,,,,,,,
ABB,ABB Ltd,Matt Smith,06/03/2018,22.80,CHF,21.86,-0.04,1.623,1.02,0.03
BABA,Alibaba Group Holding Ltd,Anna Erofeeva,05/12/2017,177.62,USD,186.78,0.05,0.000,1.04,0.05
AAPL,Apple Inc,Darren Wyy,16/01/2018,176.30,USD,261.78,0.48,5.860,1.06,0.55
ANET,Arista Networks Inc,Xu Jiawei,14/11/2017,225.50,USD,194.49,-0.14,0.000,1.02,-0.14
BHP,BHP Billiton Ltd,Matt Smith,05/12/2017,42.10,USD,50.84,0.21,7.060,1.04,0.39
BLK,BlackRock Inc,Marcus McLaney,27/02/2018,563.97,USD,485.00,-0.14,21.920,1.07,-0.11
DPZ,Domino's Pizza Inc,Dev Singh,12/12/2017,180.96,USD,285.76,0.58,4.610,1.03,0.62
EL,Estee Lauder Companies Inc,Kelvin Fang,20/02/2018,139.65,USD,193.18,0.38,2.860,1.08,0.44
FL,Foot Locker Inc,Arjun Kandola,06/03/2018,42.10,USD,40.25,-0.04,2.520,1.07,0.02
GM,General Motors Co,Matt Smith,30/01/2018,42.41,USD,35.33,-0.17,2.660,1.08,-0.11
HON,Honeywell International Inc.,Darren Wyy,13/03/2018,145.90,USD,176.79,0.21,5.670,1.07,0.27
ITRK.L,Intertek Group plc,Joshua Zeng,23/01/2018,5178.00,GBX,5504.00,0.06,181.100,1.00,0.10
KHC,Kraft Heinz Co,Joshua Zeng,19/03/2018,67.23,USD,30.54,-0.55,3.475,1.07,-0.53
MAR,Marriott International Inc,Jerry Kim,20/02/2018,140.44,USD,136.25,-0.03,3.410,1.08,-0.01
MA,Mastercard Inc,Kelvin Fang,28/11/2017,154.77,USD,282.57,0.83,2.320,1.03,0.87
OTB.L,On The Beach Group plc,Edmund Xia,30/01/2018,492.00,GBX,434.60,-0.12,4.600,1.00,-0.11
OSTK,Overstock,Anna Erofeeva,27/02/2018,64.40,USD,7.57,-0.88,0.000,1.07,-0.94
RCL,Royal Carribean Cruises Ltd,Marcus McLaney,09/01/2018,123.18,USD,119.13,-0.03,4.780,1.05,0.01
RYA.L,Ryanair Holdings,Charlotte Pinder,16/01/2018,16.53,EUR,13.69,-0.17,0.000,0.97,-0.17
SIEGY,Siemens AG,Amos Jaupi,12/12/2017,116.42,EUR,63.24,-0.46,4.329,0.97,-0.41
STM,St Microelectronics,Adam Barbarowicz,06/02/2018,18.34,EUR,23.87,0.30,0.420,0.97,0.31
SBUX,Starbucks Corp,Dev Singh,28/11/2017,55.91,USD,83.02,0.48,2.810,1.03,0.55
SUPN,Supernus Pharmaceuticals Inc,Arjun Kandola,23/01/2018,44.25,USD,21.76,-0.51,0.000,1.08,-0.55
USCR,US Concrete Inc,Charlotte Pinder,13/03/2018,65.20,USD,39.96,-0.39,0.000,1.07,-0.41
SLCA,US Silica Holdings Inc,Dev Singh,19/03/2018,25.83,USD,4.55,-0.82,0.375,1.07,-0.87
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

There are numerous ways we can select data in pandas. The first is to use square brackets to 

These individual columns are known as a series by combining the multiple series together we get a dataframe.

In [5]:
stock_pitches["Pitch Price"]

In [6]:
print(type(stock_pitches["Pitch Price"]))

print(type(stock_pitches))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

We can use two columns to return a dataframe object, this can be used to return two or more columns. 

To get the horizontal data, we use list slicing

In [7]:
stock_pitches[["Pitch Price", "Price %", "Total %"]]

,Pitch Price,Price %,Total %
Ticker,,,
ABB,22.80,-0.04,0.03
BABA,177.62,0.05,0.05
AAPL,176.30,0.48,0.55
ANET,225.50,-0.14,-0.14
BHP,42.10,0.21,0.39
BLK,563.97,-0.14,-0.11
DPZ,180.96,0.58,0.62
EL,139.65,0.38,0.44
FL,42.10,-0.04,0.02
GM,42.41,-0.17,-0.11
HON,145.90,0.21,0.27
ITRK.L,5178.00,0.06,0.10
KHC,67.23,-0.55,-0.53
MAR,140.44,-0.03,-0.01
MA,154.77,0.83,0.87
OTB.L,492.00,-0.12,-0.11
OSTK,64.40,-0.88,-0.94
RCL,123.18,-0.03,0.01
RYA.L,16.53,-0.17,-0.17
SIEGY,116.42,-0.46,-0.41
STM,18.34,0.30,0.31
SBUX,55.91,0.48,0.55
SUPN,44.25,-0.51,-0.55
USCR,65.20,-0.39,-0.41
SLCA,25.83,-0.82,-0.87
NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN

In [12]:
stock_pitches[2:5]

,Name,Associate,Pitch Date,Pitch Price,Curr,Today Price,Price %,Total Divs,Currency ?,Total %
Ticker,,,,,,,,,,
AAPL,Apple Inc,Darren Wyy,16/01/2018,176.3,USD,261.78,0.48,5.86,1.06,0.55
ANET,Arista Networks Inc,Xu Jiawei,14/11/2017,225.5,USD,194.49,-0.14,0.00,1.02,-0.14
BHP,BHP Billiton Ltd,Matt Smith,05/12/2017,42.1,USD,50.84,0.21,7.06,1.04,0.39

Whilst using the square brackets is useful we can extend our funtionality better by use the loc and iloc function 

loc = label based 

iloc = integer based

To get the information back as a dataframe, we have to put it inside multiple sets of brackets. We can also use these to splice the dataframe up across rows and columns. We can also change the order of these too.

We can use : to include all things along that axis

In [15]:
stock_pitches.loc["BABA"]

In [16]:
stock_pitches.loc[["BABA"]]

,Name,Associate,Pitch Date,Pitch Price,Curr,Today Price,Price %,Total Divs,Currency ?,Total %
Ticker,,,,,,,,,,
BABA,Alibaba Group Holding Ltd,Anna Erofeeva,05/12/2017,177.62,USD,186.78,0.05,0.0,1.04,0.05

In [17]:
stock_pitches.loc[["BABA", "FL", "GM"]]

,Name,Associate,Pitch Date,Pitch Price,Curr,Today Price,Price %,Total Divs,Currency ?,Total %
Ticker,,,,,,,,,,
BABA,Alibaba Group Holding Ltd,Anna Erofeeva,05/12/2017,177.62,USD,186.78,0.05,0.00,1.04,0.05
FL,Foot Locker Inc,Arjun Kandola,06/03/2018,42.10,USD,40.25,-0.04,2.52,1.07,0.02
GM,General Motors Co,Matt Smith,30/01/2018,42.41,USD,35.33,-0.17,2.66,1.08,-0.11

In [21]:
stock_pitches.loc[["BABA", "FL", "GM"], ["Pitch Date", "Name", "Curr"]]

,Pitch Date,Name,Curr
Ticker,,,
BABA,05/12/2017,Alibaba Group Holding Ltd,USD
FL,06/03/2018,Foot Locker Inc,USD
GM,30/01/2018,General Motors Co,USD

In [22]:
stock_pitches.loc[ :, ["Pitch Date", "Name", "Curr"]]

,Pitch Date,Name,Curr
Ticker,,,
ABB,06/03/2018,ABB Ltd,CHF
BABA,05/12/2017,Alibaba Group Holding Ltd,USD
AAPL,16/01/2018,Apple Inc,USD
ANET,14/11/2017,Arista Networks Inc,USD
BHP,05/12/2017,BHP Billiton Ltd,USD
BLK,27/02/2018,BlackRock Inc,USD
DPZ,12/12/2017,Domino's Pizza Inc,USD
EL,20/02/2018,Estee Lauder Companies Inc,USD
FL,06/03/2018,Foot Locker Inc,USD
GM,30/01/2018,General Motors Co,USD
HON,13/03/2018,Honeywell International Inc.,USD
ITRK.L,23/01/2018,Intertek Group plc,GBX
KHC,19/03/2018,Kraft Heinz Co,USD
MAR,20/02/2018,Marriott International Inc,USD
MA,28/11/2017,Mastercard Inc,USD
OTB.L,30/01/2018,On The Beach Group plc,GBX
OSTK,27/02/2018,Overstock,USD
RCL,09/01/2018,Royal Carribean Cruises Ltd,USD
RYA.L,16/01/2018,Ryanair Holdings,EUR
SIEGY,12/12/2017,Siemens AG,EUR
STM,06/02/2018,St Microelectronics,EUR
SBUX,28/11/2017,Starbucks Corp,USD
SUPN,23/01/2018,Supernus Pharmaceuticals Inc,USD
USCR,13/03/2018,US Concrete Inc,USD
SLCA,19/03/2018,US Silica Holdings Inc,USD
NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN

In [24]:
# iloc used for integers
stock_pitches.iloc[2:7, 2:6]

,Pitch Date,Pitch Price,Curr,Today Price
Ticker,,,,
AAPL,16/01/2018,176.30,USD,261.78
ANET,14/11/2017,225.50,USD,194.49
BHP,05/12/2017,42.10,USD,50.84
BLK,27/02/2018,563.97,USD,485.00
DPZ,12/12/2017,180.96,USD,285.76

We can use boolean operators on pandas dataframes. 

We will return True or False values depending on how they compare to the operator

We can then use these to select values from the initial dataframe by using square brackets

In [5]:
positive_return = stock_pitches["Total %"] > 0 

positive_return

In [6]:
stock_pitches[positive_return]

,Name,Associate,Ticker,Pitch Date,Pitch Price,Curr,Today Price,Price %,Total Divs,Currency ?,Total %
0,ABB Ltd,Matt Smith,ABB,06/03/2018,22.80,CHF,21.86,-0.04,1.623,1.02,0.03
1,Alibaba Group Holding Ltd,Anna Erofeeva,BABA,05/12/2017,177.62,USD,186.78,0.05,0.000,1.04,0.05
2,Apple Inc,Darren Wyy,AAPL,16/01/2018,176.30,USD,261.78,0.48,5.860,1.06,0.55
4,BHP Billiton Ltd,Matt Smith,BHP,05/12/2017,42.10,USD,50.84,0.21,7.060,1.04,0.39
6,Domino's Pizza Inc,Dev Singh,DPZ,12/12/2017,180.96,USD,285.76,0.58,4.610,1.03,0.62
7,Estee Lauder Companies Inc,Kelvin Fang,EL,20/02/2018,139.65,USD,193.18,0.38,2.860,1.08,0.44
8,Foot Locker Inc,Arjun Kandola,FL,06/03/2018,42.10,USD,40.25,-0.04,2.520,1.07,0.02
10,Honeywell International Inc.,Darren Wyy,HON,13/03/2018,145.90,USD,176.79,0.21,5.670,1.07,0.27
11,Intertek Group plc,Joshua Zeng,ITRK.L,23/01/2018,5178.00,GBX,5504.00,0.06,181.100,1.00,0.10
14,Mastercard Inc,Kelvin Fang,MA,28/11/2017,154.77,USD,282.57,0.83,2.320,1.03,0.87
17,Royal Carribean Cruises Ltd,Marcus McLaney,RCL,09/01/2018,123.18,USD,119.13,-0.03,4.780,1.05,0.01
20,St Microelectronics,Adam Barbarowicz,STM,06/02/2018,18.34,EUR,23.87,0.30,0.420,0.97,0.31
21,Starbucks Corp,Dev Singh,SBUX,28/11/2017,55.91,USD,83.02,0.48,2.810,1.03,0.55

In [7]:
# we could do this process in one line instead if we wanted to 
stock_pitches[stock_pitches["Total %"] > 0]

,Name,Associate,Ticker,Pitch Date,Pitch Price,Curr,Today Price,Price %,Total Divs,Currency ?,Total %
0,ABB Ltd,Matt Smith,ABB,06/03/2018,22.80,CHF,21.86,-0.04,1.623,1.02,0.03
1,Alibaba Group Holding Ltd,Anna Erofeeva,BABA,05/12/2017,177.62,USD,186.78,0.05,0.000,1.04,0.05
2,Apple Inc,Darren Wyy,AAPL,16/01/2018,176.30,USD,261.78,0.48,5.860,1.06,0.55
4,BHP Billiton Ltd,Matt Smith,BHP,05/12/2017,42.10,USD,50.84,0.21,7.060,1.04,0.39
6,Domino's Pizza Inc,Dev Singh,DPZ,12/12/2017,180.96,USD,285.76,0.58,4.610,1.03,0.62
7,Estee Lauder Companies Inc,Kelvin Fang,EL,20/02/2018,139.65,USD,193.18,0.38,2.860,1.08,0.44
8,Foot Locker Inc,Arjun Kandola,FL,06/03/2018,42.10,USD,40.25,-0.04,2.520,1.07,0.02
10,Honeywell International Inc.,Darren Wyy,HON,13/03/2018,145.90,USD,176.79,0.21,5.670,1.07,0.27
11,Intertek Group plc,Joshua Zeng,ITRK.L,23/01/2018,5178.00,GBX,5504.00,0.06,181.100,1.00,0.10
14,Mastercard Inc,Kelvin Fang,MA,28/11/2017,154.77,USD,282.57,0.83,2.320,1.03,0.87
17,Royal Carribean Cruises Ltd,Marcus McLaney,RCL,09/01/2018,123.18,USD,119.13,-0.03,4.780,1.05,0.01
20,St Microelectronics,Adam Barbarowicz,STM,06/02/2018,18.34,EUR,23.87,0.30,0.420,0.97,0.31
21,Starbucks Corp,Dev Singh,SBUX,28/11/2017,55.91,USD,83.02,0.48,2.810,1.03,0.55

We can use the numpy logical functions to further filter the data, this allows two or more conditions for out data. These work the same way they work for numpy in pandas dataframe

In [10]:
in_between = np.logical_and(stock_pitches["Total %"] > 0 , stock_pitches["Total %"] < 0.5)
in_between

In [11]:
stock_pitches[in_between]

,Name,Associate,Ticker,Pitch Date,Pitch Price,Curr,Today Price,Price %,Total Divs,Currency ?,Total %
0,ABB Ltd,Matt Smith,ABB,06/03/2018,22.80,CHF,21.86,-0.04,1.623,1.02,0.03
1,Alibaba Group Holding Ltd,Anna Erofeeva,BABA,05/12/2017,177.62,USD,186.78,0.05,0.000,1.04,0.05
4,BHP Billiton Ltd,Matt Smith,BHP,05/12/2017,42.10,USD,50.84,0.21,7.060,1.04,0.39
7,Estee Lauder Companies Inc,Kelvin Fang,EL,20/02/2018,139.65,USD,193.18,0.38,2.860,1.08,0.44
8,Foot Locker Inc,Arjun Kandola,FL,06/03/2018,42.10,USD,40.25,-0.04,2.520,1.07,0.02
10,Honeywell International Inc.,Darren Wyy,HON,13/03/2018,145.90,USD,176.79,0.21,5.670,1.07,0.27
11,Intertek Group plc,Joshua Zeng,ITRK.L,23/01/2018,5178.00,GBX,5504.00,0.06,181.100,1.00,0.10
17,Royal Carribean Cruises Ltd,Marcus McLaney,RCL,09/01/2018,123.18,USD,119.13,-0.03,4.780,1.05,0.01
20,St Microelectronics,Adam Barbarowicz,STM,06/02/2018,18.34,EUR,23.87,0.30,0.420,0.97,0.31

In [12]:
# can also write in a single line 
stock_pitches[np.logical_and(stock_pitches["Total %"] > 0 , stock_pitches["Total %"] < 0.5)]

,Name,Associate,Ticker,Pitch Date,Pitch Price,Curr,Today Price,Price %,Total Divs,Currency ?,Total %
0,ABB Ltd,Matt Smith,ABB,06/03/2018,22.80,CHF,21.86,-0.04,1.623,1.02,0.03
1,Alibaba Group Holding Ltd,Anna Erofeeva,BABA,05/12/2017,177.62,USD,186.78,0.05,0.000,1.04,0.05
4,BHP Billiton Ltd,Matt Smith,BHP,05/12/2017,42.10,USD,50.84,0.21,7.060,1.04,0.39
7,Estee Lauder Companies Inc,Kelvin Fang,EL,20/02/2018,139.65,USD,193.18,0.38,2.860,1.08,0.44
8,Foot Locker Inc,Arjun Kandola,FL,06/03/2018,42.10,USD,40.25,-0.04,2.520,1.07,0.02
10,Honeywell International Inc.,Darren Wyy,HON,13/03/2018,145.90,USD,176.79,0.21,5.670,1.07,0.27
11,Intertek Group plc,Joshua Zeng,ITRK.L,23/01/2018,5178.00,GBX,5504.00,0.06,181.100,1.00,0.10
17,Royal Carribean Cruises Ltd,Marcus McLaney,RCL,09/01/2018,123.18,USD,119.13,-0.03,4.780,1.05,0.01
20,St Microelectronics,Adam Barbarowicz,STM,06/02/2018,18.34,EUR,23.87,0.30,0.420,0.97,0.31